name: flappy_translator
description: A tool which automatically generates Flutter localization resources from CSV and Excel files.
version: 3.0.0
homepage: https://github.com/smartnsoft/FlappyTranslator
repository: https://github.com/smartnsoft/FlappyTranslator
issue_tracker: https://github.com/smartnsoft/FlappyTranslator/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  csv: ^5.0.0
  yaml: ^3.1.0
  dart_style: ^2.0.1
  excel: 
    git:
      url: https://github.com/dangabdolfo/excel.git
      ref: 3.0.0

dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0
